#!/usr/bin/env bash
BATCH_INFER_DIR=$(dirname $([ -L $0 ] && readlink -f $0 || echo $0))
BATCH_INFER_TARGET=$1
RESULTS_PREFIX=$(realpath "$2")
RESULTS_BASENAME=$(basename "$RESULTS_PREFIX")
XTRA_ARGS="$3"
LOGS_DATE=$RESULTS_PREFIX/.snakemake-eu/logs/`date +"%y-%m-%d"`
JOBNAME="batch-infer:$BATCH_INFER_TARGET=$RESULTS_BASENAME"
PROFILE="$BATCH_INFER_DIR/software/smk-simple-slurm-eu"
# Use prefix-specific config file if one exists
if [ -f "$RESULTS_PREFIX/config.yaml" ]; then
    CONFIGFILE_LOCAL="$RESULTS_PREFIX/config.yaml"
else
    CONFIGFILE_LOCAL=""
fi
cat - <<EOF
#!/usr/bin/env bash
#SBATCH --job-name=$JOBNAME
#SBATCH --ntasks=1
#SBATCH --mem-per-cpu=4G
#SBATCH --tmp=16834
#SBATCH --time=7-00:00:00
#SBATCH --output=$LOGS_DATE/$JOBNAME-%j.txt
BATCH_INFER_DIR="$BATCH_INFER_DIR"
BATCH_INFER_TARGET="$BATCH_INFER_TARGET"
RESULTS_PREFIX="$RESULTS_PREFIX"
XTRA_ARGS="$XTRA_ARGS"
module load stack/2025-06 python/3.13.0 eth_proxy
source $BATCH_INFER_DIR/.venv/bin/activate
snakemake $BATCH_INFER_TARGET $XTRA_ARGS \\
    --snakefile $BATCH_INFER_DIR/workflow/targets/$BATCH_INFER_TARGET.smk \\
    --configfile $BATCH_INFER_DIR/workflow/config/defaults.yaml $CONFIGFILE_LOCAL \\
    --profile=$PROFILE \\
    --workflow-profile=$BATCH_INFER_DIR/workflow/profiles/default \\
    --directory $RESULTS_PREFIX \\
    --rerun-triggers mtime
myjobs -j \$SLURM_JOB_ID
EOF
