[project]
name = "batch-infer"
version = "26.0-dev"
requires-python = ">=3.13"
dependencies = [
    "af3io",
    "ipykernel>=7.2.0",
    "ipywidgets>=8.1.8",
    "pooled-ppi",
    "pytest>=9.0.2",
    "scikit-learn",
    "snakemake",
    "snakemake-executor-plugin-cluster-generic",
]

[project.scripts]
batch_infer = "batch_infer.cli:cli"

[tool.uv.sources]
af3io = { workspace = true }
pooled-ppi = { workspace = true }

[tool.uv.workspace]
members = ["packages/af3io", "packages/pooled-ppi"]

[build-system]
requires = ["uv_build>=0.10.9,<0.11.0"]
build-backend = "uv_build"
