[project]
name = "batch-infer"
version = "26.0-dev"
requires-python = ">=3.13"
dependencies = [
    "af3io",
    "ipykernel",
    "ipywidgets",
    "pooled-ppi",
    "pyarrow>=24.0.0",
    "pytest",
    "scikit-learn",
    "snakemake==9.19.0",
    "snakemake-executor-plugin-cluster-generic",
]

[project.scripts]
batch-infer = "batch_infer.cli:cli"

[tool.uv.sources]
af3io = { git = "https://github.com/jurgjn/af3io.git", rev = "ed5c96f" }
pooled-ppi = { git = "https://github.com/jurgjn/pooled-ppi.git" , branch = "develop" }

[build-system]
requires = ["uv_build>=0.9.22,<0.11.0"]
build-backend = "uv_build"
