
import os, os.path, pandas as pd
from pprint import pprint

configfile: 'config/config.yaml'
include: 'rules/openfold.smk'

def read_sequences():
    with open(config['sequences']) as fh:
        sequences = fh.read().splitlines()
    return sequences

rule all:
    input:
        #expand(workpath('fasta_dir/{sequence}.fasta'), sequence=read_sequences()),
        #expand(workpath('precompute_alignments/{sequence}/sstat.tsv'), sequence=read_sequences()),
        #workpath('run_multimer/O00244,O00244/sstat.tsv'),
        #./openfold-eu --config sequences='results/tubb/tubb.txt' --rerun-triggers input --dry-run
        expand(workpath('run_multimer_output_dir/{sequences}/sstat.tsv'), sequences=read_sequences()),
