
alphafold3:
  # https://hub.docker.com/r/jurgjn/alphafold3
  #container: /cluster/project/beltrao/shared/alphafold3/images/alphafold3_b78e215.sif
  #container: /cluster/project/beltrao/shared/alphafold3/images/alphafold3_2e2ffc1.sif
  #container: /cluster/project/beltrao/shared/alphafold3/images/alphafold3_0422023.sif
  container: /cluster/project/beltrao/shared/alphafold3/images/alphafold3_v3.0.1.sif
  #container: /cluster/project/beltrao/shared/alphafold3/images/alphafold3_v3.0.0.sif
  db_dir: /cluster/project/alphafold/alphafold3
  # AlphaFold 3 default cutoff - https://github.com/google-deepmind/alphafold3/blob/main/run_alphafold.py#L206
  max_template_date: 2021-09-30
  # Turn off templates - https://pdb101.rcsb.org/motm/142
  #max_template_date: 1970-01-01
  model_dir: ~/.alphafold3_model_dir
  fetch_databases_url: https://raw.githubusercontent.com/google-deepmind/alphafold3/refs/tags/v3.0.1/fetch_databases.sh
  # https://alphafold.ebi.ac.uk/faq
  # > The minimum length is 16 amino acids
  predictions_multigpu_tokens_min: 16
  # ValueError: Number of tokens 5649 is more than the largest currently supported bucket size 5120.
  predictions_multigpu_tokens_max: 5120
  predictions_multigpu_runtime: 4h
  predictions_multigpu_buffer_time: 0.8
  msas:
    # https://snakemake.readthedocs.io/en/stable/snakefiles/rules.html#defining-retries-for-fallible-rules
    retries: 3
  predictions:
    runtime: 4h
    mem_mb: 98304
    disk_mb: 98304
    slurm_extra: "'--gpus=1 --gres=gpumem%80g'"

envmodules: # sync with batch-infer, software/smk-simple-slurm-eu/venv-create.sh
- stack/2025-06
- python/3.13.0
- eth_proxy

envmodules_offline:
- stack/2025-06
- python/3.13.0

singularity:
  container_dir: /cluster/project/beltrao/shared/alphafold3/images/
