#!/bin/bash -l
# Example:
#   ./sbatch-multimer results/example_MAPK1_DUSP6/MAPK1_DUSP6.txt | sbatch
#   ./sbatch-multimer results/tubb/tubb_subset.txt | sbatch
#   ./sbatch-multimer results/missing_pairs/structure_missing_pairs.txt | sbatch
#   ./sbatch-multimer results/helixfold3_adhoc/demo.txt | sbatch
#   ./sbatch-multimer results/helixfold3_adhoc/demo_subset.txt | sbatch
#   ./sbatch-multimer results/helixfold3_adhoc/UBIA1_HUMAN.txt | sbatch
LOGS_DATE=logs/`date +"%y-%m-%d"`
BASENAME=`basename $1`
JOBNAME=sbatch-multimer:${BASENAME%%.*}
cat - <<EOF
#!/usr/bin/env bash
#SBATCH --job-name=$JOBNAME
#SBATCH --ntasks=1
#SBATCH --mem-per-cpu=10G
#SBATCH --tmp=16834
#SBATCH --time=3-00:00:00
#SBATCH --output=$LOGS_DATE/$JOBNAME-%j.txt
module load eth_proxy
snakemake --unlock
date; time snakemake --profile smk-simple-slurm-eu --config sequences='$1' --rerun-triggers input
myjobs -j \$SLURM_JOB_ID
EOF